[mssql]
host = "127.0.0.1"
port = 1433
user = "your_mssql_user"
pass = "your_mssql_password"
database = "your_database_to_backup"

[api]
url = "http://127.0.0.1:8000/api/backups/upload"
token = "your_api_token" # Create a token in Laravel Sanctum

[backup]
temp_path = "./temp_backups"
server_name = "your_server_name"
